/// @file lib/firebase_options.dart
/// @brief Firebase configuration options for all platforms
/// @author Chatly Development Team
/// @date 2025-12-08
///
/// This file contains the Firebase configuration options that are automatically
/// generated by the Firebase CLI. It includes configuration for Android, iOS,
/// and Web platforms with appropriate settings for each environment.
/// The file is designed to be committed to version control and works across
/// all platforms in the Flutter project.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for $defaultTargetPlatform',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeNKquR8g54HRH2R1yvvAWpt5VEw9PeRc',
    appId: '1:1064092004983:android:cb3fe93b905fdf82e00c72',
    messagingSenderId: '1064092004983',
    projectId: 'run-track-37263',
    storageBucket: 'run-track-37263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_PPadGw5KHwEypGXSW22qrZW9bonXt9w',
    appId: '1:1064092004983:ios:5c8ffb65f6def63de00c72',
    messagingSenderId: '1064092004983',
    projectId: 'run-track-37263',
    storageBucket: 'run-track-37263.firebasestorage.app',
    iosClientId: '1064092004983-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.chatly.app',
  );
}
