/// @file lib/firebase_options.dart
/// @brief Firebase configuration options for all platforms
/// @author Chatly Development Team
/// @date 2025-12-08
///
/// This file contains the Firebase configuration options that are automatically
/// generated by the Firebase CLI. It includes configuration for Android, iOS,
/// and Web platforms with appropriate settings for each environment.
/// The file is designed to be committed to version control and works across
/// all platforms in the Flutter project.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for $defaultTargetPlatform',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_example_api_key_android',
    appId: '1:123456789012:android:abcdef1234567890abcdef12',
    messagingSenderId: '123456789012',
    projectId: 'chatly-production',
    storageBucket: 'chatly-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_example_api_key_ios',
    appId: '1:123456789012:ios:0987654321abcdef09876543',
    messagingSenderId: '123456789012',
    projectId: 'chatly-production',
    storageBucket: 'chatly-production.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.chatly.app',
  );
}
